import { z } from 'zod';

import type { CrudModuleConfig } from '~/lib/crud/types';

const hrEmployeeSchema = z.object({
  id: z.string().min(1, 'ID is required'),
  first_name: z.string().min(1, 'First name is required'),
  last_name: z.string().min(1, 'Last name is required'),
  preferred_name: z.string().optional(),
  gender: z.string().optional(),
  date_of_birth: z.string().optional(),
  is_minority: z.boolean().optional(),
  phone: z.string().optional(),
  email: z.string().optional(),
  company_email: z.string().optional(),
  hr_department_id: z.string().optional(),
  hr_title_id: z.string().optional(),
  sys_access_level_id: z.string().min(1, 'Access level is required'),
  team_lead_id: z.string().optional(),
  compensation_manager_id: z.string().optional(),
  hr_work_authorization_id: z.string().optional(),
  start_date: z.string().optional(),
  end_date: z.string().optional(),
  payroll_id: z.string().optional(),
  pay_structure: z.string().optional(),
  overtime_threshold: z.number().optional(),
  wc: z.string().optional(),
  payroll_processor: z.string().optional(),
  pay_delivery_method: z.string().optional(),
  site_id: z.string().optional(),
});

export const hrEmployeeConfig: CrudModuleConfig<typeof hrEmployeeSchema> = {
  tableName: 'hr_employee',
  pkType: 'text',
  pkColumn: 'id',
  orgScoped: true,

  views: {
    list: 'hr_employee',
    detail: 'hr_employee',
  },

  columns: [
    { key: 'last_name', label: 'Name', sortable: true, render: 'full_name' },
    { key: 'preferred_name', label: 'Alias' },
    { key: 'gender', label: 'Gender' },
    { key: 'date_of_birth', label: 'DOB', type: 'date', sortable: true },
    { key: 'phone', label: 'Phone' },
    { key: 'company_email', label: 'Email' },
    { key: 'hr_department_id', label: 'Department', sortable: true },
    { key: 'hr_title_id', label: 'Title', sortable: true },
    { key: 'team_lead_id', label: 'Team Lead' },
    { key: 'compensation_manager_id', label: 'Comp Manager' },
    { key: 'hr_work_authorization_id', label: 'Work Auth', sortable: true },
    { key: 'start_date', label: 'Start Date', type: 'date', sortable: true },
    { key: 'end_date', label: 'End Date', type: 'date', sortable: true },
    { key: 'payroll_id', label: 'Payroll ID' },
    { key: 'pay_structure', label: 'Pay Structure' },
    { key: 'overtime_threshold', label: 'OT Threshold' },
    { key: 'wc', label: 'WC Code' },
    { key: 'site_id', label: 'Housing Site' },
  ],

  search: {
    columns: ['first_name', 'last_name', 'company_email', 'email', 'phone'],
    placeholder: 'Search employees...',
  },

  filters: [],

  formFields: [
    {
      key: 'id',
      label: 'Employee ID',
      type: 'text',
      required: true,
      showOnCreate: true,
      showOnEdit: false,
    },
    { key: 'first_name', label: 'First Name', type: 'text', required: true },
    { key: 'last_name', label: 'Last Name', type: 'text', required: true },
    { key: 'preferred_name', label: 'Preferred Name', type: 'text' },
    {
      key: 'gender',
      label: 'Gender',
      type: 'select',
      options: [
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
      ],
    },
    { key: 'date_of_birth', label: 'Date of Birth', type: 'date' },
    { key: 'is_minority', label: 'Minority', type: 'boolean' },
    { key: 'phone', label: 'Phone', type: 'text' },
    { key: 'email', label: 'Personal Email', type: 'text' },
    { key: 'company_email', label: 'Company Email', type: 'text' },
    {
      key: 'hr_department_id',
      label: 'Department',
      type: 'fk',
      fkTable: 'hr_department',
      fkLabelColumn: 'name',
    },
    {
      key: 'hr_title_id',
      label: 'Title',
      type: 'fk',
      fkTable: 'hr_title',
      fkLabelColumn: 'name',
    },
    {
      key: 'sys_access_level_id',
      label: 'Access Level',
      type: 'fk',
      fkTable: 'sys_access_level',
      fkLabelColumn: 'name',
      required: true,
    },
    {
      key: 'team_lead_id',
      label: 'Team Lead',
      type: 'fk',
      fkTable: 'hr_employee',
      fkLabelColumn: 'last_name',
    },
    {
      key: 'compensation_manager_id',
      label: 'Compensation Manager',
      type: 'fk',
      fkTable: 'hr_employee',
      fkLabelColumn: 'last_name',
    },
    {
      key: 'hr_work_authorization_id',
      label: 'Work Authorization',
      type: 'fk',
      fkTable: 'hr_work_authorization',
      fkLabelColumn: 'name',
    },
    { key: 'start_date', label: 'Start Date', type: 'date' },
    { key: 'end_date', label: 'End Date', type: 'date' },
    { key: 'payroll_id', label: 'Payroll ID', type: 'text' },
    {
      key: 'pay_structure',
      label: 'Pay Structure',
      type: 'select',
      options: [
        { value: 'hourly', label: 'Hourly' },
        { value: 'salary', label: 'Salary' },
      ],
    },
    { key: 'overtime_threshold', label: 'OT Threshold (hrs/week)', type: 'number' },
    { key: 'wc', label: 'WC Code', type: 'text' },
    { key: 'payroll_processor', label: 'Payroll Processor', type: 'text' },
    { key: 'pay_delivery_method', label: 'Pay Delivery Method', type: 'text' },
    {
      key: 'site_id',
      label: 'Housing Site',
      type: 'fk',
      fkTable: 'org_site',
      fkLabelColumn: 'name',
    },
  ],

  schema: hrEmployeeSchema,
};
