CREATE TABLE IF NOT EXISTS fsafe_emp_test (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          TEXT NOT NULL REFERENCES org(id) ON DELETE CASCADE,
    farm_id         TEXT REFERENCES farm(id),
    site_id         TEXT REFERENCES site(id),
    task_tracker_id UUID REFERENCES hr_task_tracker(id),

    -- Test configuration
    test_name_id    TEXT NOT NULL REFERENCES fsafe_emp_test_name(id),
    test_method     TEXT,
    test_type       TEXT NOT NULL CHECK (test_type IN ('initial', 'retest', 'vector')),
    test_status     TEXT NOT NULL DEFAULT 'pending' CHECK (test_status IN ('pending', 'in_progress', 'completed')),

    -- Sample collection
    sampled_at      TIMESTAMPTZ,
    sampled_by      TEXT REFERENCES hr_employee(id),

    -- Lab processing
    completed_at    TIMESTAMPTZ,

    -- Results
    result_enum     TEXT,
    result_numeric  NUMERIC,
    results_pass    BOOLEAN,
    warning_message TEXT,
    fail_code       TEXT,

    -- Retest / vector test linkage
    original_test_id    UUID REFERENCES fsafe_emp_test(id),

    -- Verification
    verified_by         TEXT        REFERENCES hr_employee(id),
    verified_at         TIMESTAMPTZ,

    -- Additional
    notes               TEXT,
    is_system_generated BOOLEAN NOT NULL DEFAULT false,

    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by      TEXT
);

CREATE INDEX idx_fsafe_emp_test_org ON fsafe_emp_test (org_id);
CREATE INDEX idx_fsafe_emp_test_tracker ON fsafe_emp_test (task_tracker_id);
CREATE INDEX idx_fsafe_emp_test_site ON fsafe_emp_test (site_id);
CREATE INDEX idx_fsafe_emp_test_name ON fsafe_emp_test (test_name_id);
CREATE INDEX idx_fsafe_emp_test_original ON fsafe_emp_test (original_test_id);
CREATE INDEX idx_fsafe_emp_test_status ON fsafe_emp_test (org_id, test_status);

COMMENT ON TABLE fsafe_emp_test IS 'EMP test results. Each row is a single test event. Retests and vector tests link back to the original failing test via original_test_id.';
COMMENT ON COLUMN fsafe_emp_test.id IS 'Unique identifier for the test result record';
COMMENT ON COLUMN fsafe_emp_test.org_id IS 'Owning organization for RLS filtering';
COMMENT ON COLUMN fsafe_emp_test.farm_id IS 'Farm where the sample was collected';
COMMENT ON COLUMN fsafe_emp_test.site_id IS 'Site where the sample was collected; zone classification is stored on the site record';
COMMENT ON COLUMN fsafe_emp_test.task_tracker_id IS 'Task tracker activity this test result belongs to; links ATP results back to the checklist session for full form reconstruction';
COMMENT ON COLUMN fsafe_emp_test.test_name_id IS 'Test name and configuration used for this test event';
COMMENT ON COLUMN fsafe_emp_test.test_method IS 'Test method used, selected from the test name methods list (e.g. PCR, Culture)';
COMMENT ON COLUMN fsafe_emp_test.test_type IS 'Type of test: initial (first run), retest (triggered by initial fail), vector (triggered by retest fail)';
COMMENT ON COLUMN fsafe_emp_test.test_status IS 'Workflow status: pending, in_progress, completed';
COMMENT ON COLUMN fsafe_emp_test.sampled_at IS 'Timestamp when the sample was collected';
COMMENT ON COLUMN fsafe_emp_test.sampled_by IS 'Employee who collected the sample';
COMMENT ON COLUMN fsafe_emp_test.completed_at IS 'Timestamp when the lab completed processing the sample';
COMMENT ON COLUMN fsafe_emp_test.result_enum IS 'Enum result value selected from test_name enum_options when result_type is enum';
COMMENT ON COLUMN fsafe_emp_test.result_numeric IS 'Numeric result value when result_type is numeric; frontend converts detection limit strings (e.g. <1, >2419) to numeric values before submission';
COMMENT ON COLUMN fsafe_emp_test.results_pass IS 'Whether the result meets the pass criteria defined on the test name';
COMMENT ON COLUMN fsafe_emp_test.warning_message IS 'Warning message displayed when the result fails';
COMMENT ON COLUMN fsafe_emp_test.fail_code IS 'Human-readable failure code assigned to this test result (e.g. LM-001)';
COMMENT ON COLUMN fsafe_emp_test.original_test_id IS 'Reference to the initial test that triggered this retest or vector test; null for initial tests';
COMMENT ON COLUMN fsafe_emp_test.verified_by IS 'Employee who verified the test result';
COMMENT ON COLUMN fsafe_emp_test.verified_at IS 'Timestamp when the test result was verified';
COMMENT ON COLUMN fsafe_emp_test.notes IS 'Free-text notes about the test event';
COMMENT ON COLUMN fsafe_emp_test.is_system_generated IS 'Whether this record was auto-generated by the system when a prior test failed';
COMMENT ON COLUMN fsafe_emp_test.is_active IS 'Soft delete flag; false hides the record from active use';
COMMENT ON COLUMN fsafe_emp_test.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN fsafe_emp_test.created_by IS 'Email of the user who created the record';
COMMENT ON COLUMN fsafe_emp_test.updated_at IS 'Timestamp when the record was last updated';
COMMENT ON COLUMN fsafe_emp_test.updated_by IS 'Email of the user who last updated the record';
