CREATE TABLE IF NOT EXISTS hr_training_attendee (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          TEXT NOT NULL REFERENCES org(id) ON DELETE CASCADE,
    training_id     UUID NOT NULL REFERENCES hr_training(id) ON DELETE CASCADE,
    employee_id     TEXT NOT NULL REFERENCES hr_employee(id),

    attended_training           BOOLEAN NOT NULL DEFAULT false,
    signed_at                   TIMESTAMPTZ,

    certification_number        TEXT,
    certification_issued_on     DATE,
    certification_expires_on    DATE,
    certificate_url             TEXT,

    notes               TEXT,
    is_system_generated BOOLEAN NOT NULL DEFAULT false,

    is_active       BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by      TEXT,

    CONSTRAINT uq_hr_training_attendee UNIQUE (training_id, employee_id)
);

CREATE INDEX idx_hr_training_attendee_training ON hr_training_attendee (training_id);
CREATE INDEX idx_hr_training_attendee_employee ON hr_training_attendee (employee_id);
CREATE INDEX idx_hr_training_attendee_org ON hr_training_attendee (org_id);

COMMENT ON TABLE hr_training_attendee IS 'Individual attendance and certification records for each employee per training session. One row per employee per training.';
COMMENT ON COLUMN hr_training_attendee.id IS 'Unique identifier for the attendee record';
COMMENT ON COLUMN hr_training_attendee.org_id IS 'Owning organization for RLS filtering';
COMMENT ON COLUMN hr_training_attendee.training_id IS 'Training session this attendance record belongs to';
COMMENT ON COLUMN hr_training_attendee.employee_id IS 'Employee who attended or was scheduled to attend the training';
COMMENT ON COLUMN hr_training_attendee.attended_training IS 'Whether the employee attended the training session';
COMMENT ON COLUMN hr_training_attendee.signed_at IS 'Timestamp when the employee signed the training attendance record';
COMMENT ON COLUMN hr_training_attendee.certification_number IS 'Certification number issued to the employee upon completion';
COMMENT ON COLUMN hr_training_attendee.certification_issued_on IS 'Date the certification was issued to the employee';
COMMENT ON COLUMN hr_training_attendee.certification_expires_on IS 'Date the employee certification expires';
COMMENT ON COLUMN hr_training_attendee.certificate_url IS 'URL or path to the issued certificate document';
COMMENT ON COLUMN hr_training_attendee.notes IS 'Free-text notes about this attendee record';
COMMENT ON COLUMN hr_training_attendee.is_system_generated IS 'Whether this record was auto-generated by the system rather than manually created';
COMMENT ON COLUMN hr_training_attendee.is_active IS 'Soft delete flag; false hides the record from active use';
COMMENT ON COLUMN hr_training_attendee.created_at IS 'Timestamp when the record was created';
COMMENT ON COLUMN hr_training_attendee.created_by IS 'Email of the user who created the record';
COMMENT ON COLUMN hr_training_attendee.updated_at IS 'Timestamp when the record was last updated';
COMMENT ON COLUMN hr_training_attendee.updated_by IS 'Email of the user who last updated the record';
